version: '3.7'

services:
    alquileres:
      build: alquileres/
      ports:
        - "8080:8080"
      depends_on:
        - mysql
        - rabbitmq

    estaciones:
      build: estaciones/
      ports: 
        - "8081:8081"
      environment:
        - SPRING_DATA_MONGODB_URI=mongodb://root:1234@mongo:27017/dbEstaciones?authSource=admin
      depends_on:
        - mongo
        - rabbitmq

    usuarios:
      build: LoginApi/
      ports:
        - "5259:5259"
      environment:
        - ASPNETCORE_MONGODB_CONNECTION_STRING=mongodb://root:1234@mongo:27017/dbUsuarios?authSource=admin
      depends_on:
        - mongo

    pasarela:
      build: pasarela/
      ports: 
        - "8082:8082"

    mongo: 
      image: mongo
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: 1234

    mongo-express: 
      image: mongo-express
      restart: always
      ports:
        - 8083:8081
      environment:
        ME_CONFIG_BASICAUTH_USERNAME: admin
        ME_CONFIG_BASICAUTH_PASSWORD: pass
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
        ME_CONFIG_MONGODB_URL: mongodb://root:1234@mongo:27017
      depends_on:
        - mongo

    mysql:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: mysql123
        MYSQL_DATABASE: alquileres
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - "8084:80"
      environment:
        PMA_HOST: mysql
        PMA_USER: root
        PMA_PASSWORD: mysql123
      depends_on:
        - mysql

    rabbitmq:
      image: rabbitmq:3-management
      ports: 
        - "15672:15672"
        - "5672:5672"
      environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq
      restart: always


volumes:
  mongo_data:
  mysql_data:
  rabbitmq_data:
